key_auth.settings:
  type: config_object
  label: 'Key authentication settings.'
  mapping:
    auto_generate_keys:
      type: boolean
      label: 'Generate keys automatically for new users'
    key_length:
      type: integer
      label: 'Key length'
    param_name:
      type: string
      label: 'Parameter name'
    detection_methods:
      type: sequence
      label: 'Detection methods'
      sequence:
        type: string
        label: 'Detection method'
