<?php

/**
 * @file
 * Contains decoupled_kit_metatag.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function decoupled_kit_metatag_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the decoupled_kit_metatag module.
    case 'help.page.decoupled_kit_metatag':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Metatag module integration.') . '</p>';
      return $output;

    default:
  }
}
