<?php

/**
 * @file
 * Contains decoupled_kit_breadcrumb.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function decoupled_kit_breadcrumb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the decoupled_kit_breadcrumb module.
    case 'help.page.decoupled_kit_breadcrumb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple breadcrumbs.') . '</p>';
      return $output;

    default:
  }
}
