workbench_moderation.moderation_state.*.third_party.type_style: &defaults
  type: mapping
  label: 'Type Style settings'
  mapping:
    color:
      type: string
      label: 'A color code represented in hexadecimal (i.e. #000000)'
    icon:
      type: string
      label: 'The icon name'

workbench_moderation.moderation_state_transition.*.third_party.type_style:
  <<: *defaults
