block_content.type.*.third_party.type_style: &defaults
  type: mapping
  label: 'Type Style settings'
  mapping:
    color:
      type: string
      label: 'A color code represented in hexadecimal (i.e. #000000)'
    icon:
      type: string
      label: 'The icon name'

node.type.*.third_party.type_style:
  <<: *defaults

taxonomy.vocabulary.*.third_party.type_style:
  <<: *defaults

media.type.*.third_party.type_style:
  <<: *defaults

file_entity.type.*.third_party.type_style:
  <<: *defaults

type_style.settings:
  type: config_object
  label: 'Type Style global settings'
  mapping:
    icon_type:
      type: text
      label: 'Icon type'
    use_cdn:
      type: boolean
      label: 'Use a CDN'
