field.widget.settings.daterange_duration:
  type: mapping
  label: 'Date range duration widget settings'
  mapping:
    default_duration:
      type: mapping
      label: 'Default duration'
      mapping:
        y:
          type: integer
          label: 'Years'
        m:
          type: integer
          label: 'Months'
        d:
          type: integer
          label: 'Days'
        h:
          type: integer
          label: 'Hours'
        i:
          type: integer
          label: 'Minutes'
        s:
          type: integer
          label: 'Seconds'
    duration_granularity:
      type: granularity
      label: 'Duration granularity'
    time_increment:
      type: integer
      label: 'Time increments'
